apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: demo
  name: demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: azureprice.azurecr.io/azurecalc:257
          ports:
          - containerPort: 80
            protocol: TCP
      imagePullSecrets:
      - name: registrysecret